# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f182b9fe5fc64d806d779c4aa0e99cf697dda09bfd9b84c4cc1fafdec6031435b6a11cbecfc32fa54350ab2a06281ae37771c3bd91128a9646c7559d1999b30c

test:
  secret_key_base: a119d677bad0c7ec4d1fb40f422a0983daf3616bd7bd315094d3b22f25b7acd4ff53bed9fb7182f8dd472066d222cc0c0d9f529b04c6e6b95e821decab054834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
